### ISSUE TITLE
Maybe provide shell utility? for sending adhoc resources?

### ISSUE THREAD

**Issue by phillmv** [appcanary/appcanary.rb#13]
i.e. herp derp i'm on a linux and i want to try this out w/o installing the agent

**Comment by j0ni** [comment]
closed by #17

Note that this conflates two capabilities, I will open another issue for the shipping of none `Gemfile.lock` resources via the command line.

**Comment by j0ni** [comment]
The arbitrary resources part of this is now covered by #20
